name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      number1:
        description: "Enter Number One"
        type: number
        required: true
        default: 5
      number2:
        description: "Enter Number Two"
        type: number
        required: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: dispalying numbers
        run: |
          echo "Number1 value is ${{ inputs.number1}}"
          echo "Number2 value is ${{ inputs.number2}}"
          
        
